import {
    VerticalBox,
    HorizontalBox,
    ScrollView,
    ListView,
} from "std-widgets.slint";
import { Button } from "button.slint";
import { JsonRow, JsonValue } from "json.slint";

export component AppWindow inherits Window {
    callback set_filter(string);
    callback select_file();
    callback key_press(KeyEvent);
    callback check_filter(string);
    property <image> file_img: @image-url("images/file.svg");
    property <image> search_img: @image-url("images/search.svg");
    in property <[JsonValue]> json_values;
    in property <bool> is_regex_valid: true;
    out property <int> current_value: values.viewport-y / -30px;

    default-font-size: 20px;
    background: #222;

    min-width: 700px;
    min-height: 300px;

    public function toolbar_toggle() {
        toolbar.height = toolbar.height == 50px ? 0px : 50px;
    }
    public function focus_filter() {
        filter.focus();
        toolbar.height = 50px;
    }
    public function move_to(id: int) {
        values.viewport-y = - (id * 30px);
    }

    VerticalLayout {
        width: 100%;

        toolbar := Rectangle {
            width: 100%;
            height: 50px;
            background: #333;
            clip: true;

            HorizontalLayout {
                width: 100%;
                alignment: stretch;
                padding: 5px;
                padding-left: 10px;
                padding-right: 10px;
                spacing: 10px;

                Rectangle {
                    width: 50px;
                    Button {
                        width: 100%;
                        height: 100%;
                        icon: file_img;
                        clicked => {
                            select_file();
                        }
                    }
                }

                Rectangle {
                    width: 50px;
                    Button {
                        width: 100%;
                        height: 100%;
                        icon: search_img;
                        clicked => {
                            set_filter(filter.text);
                            input.focus();
                        }
                    }
                }

                Rectangle {
                    background: is_regex_valid ? #555 : #a33;
                    border-color: #000;
                    border-width: 1px;
                    border-radius: 5px;
                    HorizontalBox {
                        padding: 5px;
                        filter := TextInput {
                            single-line: true;
                            wrap: char-wrap;
                            vertical-alignment: center;
                            accepted => {
                                set_filter(filter.text);
                                input.focus();
                            }
                            edited => {
                                check_filter(filter.text);
                            }
                        }
                    }
                }
            }

            animate height {
                duration: 100ms;
                easing: ease-in-out-expo;
            }
        }

        Rectangle {
            height: 5px;
            background: ta_toolbar.has-hover ? #f11 : #111;
            ta_toolbar := TouchArea {
                clicked => {
                    toolbar_toggle();
                }
            }

            animate background {
                duration: 200ms;
                easing: ease-in-out-expo;
            }
        }

        Rectangle {
            background: #111;
            values := ListView {
                for k[i] in root.json_values: JsonRow {
                    value: k;
                }
            }
        }
    }

    input := FocusScope {
        key-pressed(event) => {
            key_press(event);
            return EventResult.accept;
        }
    }
}
