import {
    VerticalBox,
    HorizontalBox,
    ScrollView,
    ListView,
} from "std-widgets.slint";
import { Button } from "button.slint";

enum ValueType {
  null,
  number,
  bool,
  string,
  array,
  object,
}
export struct JsonValue {
  name: string,
  value: string,
  level: int,
  value_type: ValueType,
  id: int,
}
component JsonRow {
    in property <string> name;
    in property <string> value;
    in property <int> level;
    in property <ValueType> type;

    property <length> indent:level * 25px;
    Rectangle {
        width: 100%;

        VerticalLayout {
            HorizontalLayout {
                padding-left: indent;
                alignment: start;

                if name != "": Text {
                    text: name + ": ";
                }

                Text {
                    text: value;
                }
            }

            Rectangle {
                height: 1px;
                background: #222;
            }
        }
    }
}

export component AppWindow inherits Window {
    callback set_filter(string);
    callback select_file();
    callback key_press(KeyEvent);
    callback check_filter(string);
    property <image> file_img: @image-url("images/file.svg");
    property <image> search_img: @image-url("images/search.svg");
    in property <[JsonValue]> json_values;
    in property <bool> is_regex_valid: true;
    default-font-size: 20px;
    background: #222;

    public function toolbar_toggle() {
        toolbar.height = toolbar.height == 50px ? 0px : 50px;
    }
    public function focus_filter() {
        filter.focus();
        toolbar.height = 50px;
    }

    VerticalLayout {
        width: 100%;

        toolbar := Rectangle {
            width: 100%;
            height: 50px;
            background: #333;
            clip: true;

            HorizontalLayout {
                width: 100%;
                alignment: stretch;
                padding: 5px;
                padding-left: 10px;
                padding-right: 10px;
                spacing: 10px;

                Rectangle {
                    width: 50px;
                    Button {
                        width: 100%;
                        height: 100%;
                        icon: file_img;
                        clicked => {
                            select_file();
                        }
                    }
                }

                Rectangle {
                    width: 50px;
                    Button {
                        width: 100%;
                        height: 100%;
                        icon: search_img;
                        clicked => {
                            set_filter(filter.text);
                        }
                    }
                }

                Rectangle {
                    background: is_regex_valid ? #555 : #a33;
                    border-color: #000;
                    border-width: 1px;
                    border-radius: 5px;
                    HorizontalBox {
                        padding: 5px;
                        filter := TextInput {
                            single-line: true;
                            wrap: char-wrap;
                            vertical-alignment: center;
                            accepted => {
                                set_filter(filter.text);
                            }
                            edited => {
                                check_filter(filter.text);
                            }
                        }
                    }
                }
            }

            animate height {
                duration: 100ms;
                easing: ease-in-out-expo;
            }
        }

        Rectangle {
            height: 5px;
            background: ta_toolbar.has-hover ? #f11 : #111;
            ta_toolbar := TouchArea {
                clicked => {
                    toolbar_toggle();
                }
            }

            animate background {
                duration: 200ms;
                easing: ease-in-out-expo;
            }
        }

        Rectangle {
            background: #111;
            ListView {
                min-width: 200px;
                min-height: 200px;
                for k in root.json_values: JsonRow {
                    value: k.value;
                    name: k.name;
                    level: k.level;
                    type: k.value_type;
                }
            }
        }
    }

    FocusScope {
        key-pressed(event) => {
            key_press(event);
            return EventResult.accept;
        }
    }
}
