export enum ValueType {
  null,
  number,
  bool,
  string,
  array,
  object,
}
export struct JsonValue {
  name: string,
  value: string,
  level: int,
  value_type: ValueType,
  id: int,

  // Flags
  in_filter: bool,
}

export component JsonRow inherits Rectangle {
    in property <JsonValue> value;

    property <length> indent:value.level * 10px;
    height: 30px;
    width: 100%;

    background: value.in-filter ? #933 : #333;
    VerticalLayout {
        spacing: 0;
        HorizontalLayout {
            padding-left: indent;
            alignment: start;

            if value.name != "": Text {
                text: value.name + ": ";
            }

            Rectangle {
                value_input := TextInput {
                    text: value.value;
                }

                states [
                    focussed when value_input.has-focus: {
                        background: #444;
                    }
                ]
            }
        }

        Rectangle {
            height: 1px;
            background: #222;
        }
    }

    ta := TouchArea { }

    states [
        hover when ta.has-hover: {
            background: #555;
        }
    ]
}
