export enum ValueType {
  null,
  number,
  bool,
  string,
  array,
  object,
}
export struct JsonValue {
  name: string,
  value: string,
  level: int,
  value_type: ValueType,
  id: int,

  // Flags
  in_filter: bool,
}

export component JsonRow {
    in property <JsonValue> value;

    property <length> indent:value.level * 10px;
    height: 30px;
    Rectangle {
        width: 100%;
        height: 100%;

        background: value.in-filter ? #933 : #333;
        VerticalLayout {
            spacing: 0;
            HorizontalLayout {
                padding-left: indent;
                alignment: start;

                if value.name != "": Text {
                    text: value.name + ": ";
                }

                Text {
                    text: value.value;
                }
            }

            Rectangle {
                height: 1px;
                background: #222;
            }
        }
    }
}
