export enum ValueType {
  null,
  number,
  bool,
  string,
  array,
  object,
}
export struct JsonValue {
  name: string,
  value: string,
  level: int,
  value_type: ValueType,
  id: int,

  // Flags
  in_filter: bool,
}

export component JsonRow inherits Rectangle {
    in property <JsonValue> value;

    property <bool> is-array: value.value == "{" || value.value == "[";
    property <length> indent:value.level * 10px;
    height: 30px;
    width: 100%;

    background: value.in-filter ? #933 : #333;
    VerticalLayout {
        spacing: 0;
        HorizontalLayout {
            padding-left: indent;
            alignment: start;

            if value.name != "": Text {
                text: value.name + ": ";
            }
            if is-array: Text {
                text: value.value;
            }

            if !is-array: Rectangle {
                border-color: #bbb;
                border-width: 1px;

                TextInput {
                    text: value.value;
                    input-type: text;
                    width: parent.width;
                }
            }
        }

        Rectangle {
            height: 1px;
            background: #222;
        }

        // ta := TouchArea { }
    //
    // states [
    //     hover when ta.has-hover: {
    //         background: #555;
    //     }
    // ]
    }
}
